apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reverse-proxy2
  name: reverse-proxy2
spec:
  containers:
  - image: nginx
    name: reverse-proxy
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
